import os                                                                                                                                                                                                                                                                 
from flask import Flask, render_template, request, redirect, url_for, session
from dotenv import load_dotenv                                                                                                                                                                                                                                              
import database                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                              
load_dotenv()                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                              
app = Flask(__name__)                                                                                                                                                                                                                                                     
app.secret_key = os.environ.get("SECRET_KEY", "fallback-nur-fuer-development")

@app.before_request                                                                                                                                                                                                                                                         
def setup():                                                                                                                                                                                                                                                                
    """Stellt sicher, dass die DB beim ersten Request existiert."""                                                                                                                                                                                                         
    database.init_db()

@app.route("/", methods=["GET", "POST"])                                                                                                                                                                                                                                    
def login():                                                                                                                                                                                                                                                                
    if "username" in session:                                                                                                                                                                                                                                                   
        return redirect(url_for("dashboard"))              
    if request.method == "POST":                                                                                                                                                                                                                                                
        username = request.form.get("username", "").strip()                                                                                                                                                                                                                     
        password = request.form.get("password", "")                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                              
        user = database.get_user(username)                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                              
        if user and database.verify_password(password, user["password_hash"]):                                                                                                                                                                                                  
            session["username"] = user["username"]                                                                                                                                                                                                                              
            return redirect(url_for("dashboard"))                                                                                                                                                                                                                             
        else:
            error = "Ungültige Anmeldedaten."              
    return render_template("login.html", error=error)       

@app.route("/dashboard")                                                                                                                                                                                                                                                    
def dashboard():                                                                                                                                                                                                                                                            
    if "username" not in session:                                                                                                                                                                                                                                           
        return redirect(url_for("login"))                                                                                                                                                                                                                                   
    return render_template("dashboard.html", username=session["username"])             

                                                                                                                                                                                                                                                       
@app.route("/logout")                                                                                                                                                                                                                                                       
def logout():                                                                                                                                                                                                                                                               
    session.clear()                                                                                                                                                                                                                                                         
    return redirect(url_for("login"))    

@app.route("/register", methods=["GET", "POST"])                                                                                                                                                                                                                            
def register():                                                                                                                                                                                                                                                             
    message = None                                                                                                                                                                                                                                                          
    if request.method == "POST":                                                                                                                                                                                                                                            
        username = request.form.get("username", "").strip()                                                                                                                                                                                                                 
        password = request.form.get("password", "")                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                              
        if not username or not password:                                                                                                                                                                                                                                    
            message = "Bitte Username und Passwort angeben."                                                                                                                                                                                                                
        elif len(password) < 8:                                                                                                                                                                                                                                             
            message = "Passwort muss mindestens 8 Zeichen haben."                                                                                                                                                                                                           
        else:                                                                                                                                                                                                                                                               
            success = database.create_user(username, password)                                                                                                                                                                                                              
            if success:                                                                                                                                                                                                                                                     
                  message = f"User '{username}' wurde erfolgreich angelegt."                                                                                                                                                                                                  
            else:                                                                                                                                                                                                                                                           
                message = f"Username '{username}' ist bereits vergeben."                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                              
    return render_template("register.html", message=message)                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                              
if __name__ == "__main__":
    app.run(debug=True)